version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql

  app:
    build: .
    image: wordpress
    ports:
      - "8080:80"
    links:
      - db
    volumes:
      - ./wp-core:/var/www/html:cached
      - ./wp-theme:/var/www/html/wp-content/themes/development-theme:cached
    depends_on:
      - db

volumes:
  db:
