version: '3'
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql

  app:
    build: ./dockerfiles/centos6-lap
    image: centos6-lap
    ports:
      - "80:80"
    links:
      - db
    volumes:
      - ./wp-core:/var/www/html:cached
      - ./wp-theme:/var/www/html/wp-content/themes/development:cached
      - ./logs/httpd:/var/log/httpd:cached
    depends_on:
      - db
volumes:
  db:
